name: Update Helm Repository Index

on:
  push:
    branches:
      - main
    paths:
      - 'charts/**'  # Runs only if Helm charts change
  workflow_dispatch:  # Allows manual trigger

jobs:
  update-helm-index:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.11.1

      - name: Package Helm Charts
        run: |
          mkdir -p packaged
          for chart in charts/*; do
            if [ -d "$chart" ]; then
              helm package "$chart" -d packaged/
            fi
          done

      - name: Update Helm Index
        run: |
          helm repo index . --url https://arconixforge.github.io/helm-charts/

      - name: Debug GitHub Secret
        run: |
          echo "Checking GitHub Secret..."
          echo "GH_PAT=${{ secrets.GH_PAT }}" | sed 's/./& /g'

      - name: Commit and Push Changes
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          echo "💡 Debugging GitHub Actions Push Issue"
          
          git config --global user.email "arconixforge@gmail.com"
          git config --global user.name "ArconixForge"

          # Ensure authentication uses PAT correctly
          git remote remove origin || true
          git remote add origin https://${GH_PAT}@github.com/ArconixForge/helm-charts.git

          # Fetch latest changes
          git fetch origin main
          git checkout main

          git add .
          git commit -m "Auto-update Helm index.yaml and package charts" || echo "No changes to commit"
          
          # Force push using PAT
          echo "🚀 Attempting to push changes..."
          GIT_TRACE=1 GIT_CURL_VERBOSE=1 git push origin main || (echo "❌ Git Push Failed!" && exit 1)