name: Helm Chart Release Automation

on:
  push:
    branches:
      - main
    paths:
      - 'charts/**'  # Runs only if Helm charts change
  workflow_dispatch:  # Allows manual trigger

# Add permissions to allow the workflow to push to the repository and create releases
permissions:
  contents: write

jobs:
  helm-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all history for proper versioning

      - name: Setup Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.11.1

      - name: Extract Chart Version
        id: chart_version
        run: |
          VERSION=$(grep '^version:' charts/kube-resource-collector/Chart.yaml | awk '{print $2}')
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "Chart version: $VERSION"

      - name: Package Helm Chart
        run: |
          mkdir -p packaged
          helm package charts/kube-resource-collector -d packaged/
          echo "Created package: packaged/kube-resource-collector-${{ env.VERSION }}.tgz"

      - name: Update Helm Index
        run: |
          helm repo index . --url https://arconixforge.github.io/helm-charts/
          echo "Updated Helm repository index"

      - name: Commit & Push Changes
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          
          git add .
          git commit -m "Release: Helm chart v${{ env.VERSION }}" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: "v${{ env.VERSION }}"
          name: "Helm Chart v${{ env.VERSION }}"
          body: |
            # Helm Chart Release v${{ env.VERSION }}
            
            This release includes:
            - kube-resource-collector v${{ env.VERSION }}
            
            ## Installation
            ```bash
            helm repo add arconixforge https://arconixforge.github.io/helm-charts
            helm repo update
            helm install kube-resource-collector arconixforge/kube-resource-collector
            ```
          files: packaged/kube-resource-collector-${{ env.VERSION }}.tgz
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Notify ArtifactHub
        run: |
          # Replace with your actual ArtifactHub webhook ID
          ARTIFACTHUB_WEBHOOK_ID="9b813108-e7fd-47e2-a6d3-e6dd66fd0880"
          echo "Notifying ArtifactHub of new release..."
          curl -X POST "https://artifacthub.io/api/v1/webhooks/call?webhook_id=$ARTIFACTHUB_WEBHOOK_ID"
          